### ISSUE TITLE
issue with the url format

### ISSUE THREAD

**Issue by HYPETAN** [rohit-iwnl/PitchForkPilot#6]
i have done the setup and tried to start applying for jobs, but when i enter the URL it says the URL format is wrong and enter the required format. i directly copy-pasted it from the official asu on campus website. what is the actual required format?
![Screenshot 2024-08-06 132154](https://github.com/user-attachments/assets/fec36d39-404e-4cc7-9653-0e06f495df2d)

**Comment by rohit-iwnl** [comment]
Hey

The problem is with the regex check. Try commenting out line the whole if-else block at 119 to 124 and check

Maybe they changed the url formats

Note: I am not actively developing it or updating the repo.
